import type { ErrorMapEntry } from "./types";

export const ERROR_MAP: Record<string, ErrorMapEntry> = {
  PROFILE_FAILED: {
    title: "We couldn't analyze this data",
    explanation: "FACILIO couldn't finish analyzing this version.",
    consequence: "Your dataset is still available and unchanged.",
    retrySafe: true,
    learnHref: "/learn#data",
    learnLabel: "What Analyze does",
    dataSafety: "unchanged",
  },
  PROFILING_FAILED: {
    title: "We couldn't analyze this data",
    explanation: "FACILIO couldn't finish analyzing this version.",
    consequence: "Your dataset is still available and unchanged.",
    retrySafe: true,
    learnHref: "/learn#data",
    learnLabel: "What Analyze does",
    dataSafety: "unchanged",
  },
  PROFILE_NOT_READY: {
    title: "Analyze this version first",
    explanation: "Guided Cleanup uses FACILIO's analysis of the selected version.",
    consequence: "Your data was not changed.",
    retrySafe: false,
    learnHref: "/learn#data",
    learnLabel: "What Analyze does",
    dataSafety: "unchanged",
  },
  PROFILE_NOT_FOUND: {
    title: "Analyze this version first",
    explanation: "There is no completed analysis for this version yet.",
    consequence: "Your data was not changed.",
    retrySafe: true,
    learnHref: "/learn#data",
    learnLabel: "What Analyze does",
    dataSafety: "unchanged",
  },
  UNSUPPORTED_FILE_TYPE: {
    title: "We couldn't add this file",
    explanation: "FACILIO supports CSV, Excel and JSON files.",
    consequence: "The file wasn't added.",
    retrySafe: true,
    learnHref: "/learn#bring",
    learnLabel: "Bring in your data",
    dataSafety: "not-added",
  },
  FILE_TOO_LARGE: {
    title: "This file is too large",
    explanation: "The file is larger than FACILIO's current upload limit.",
    consequence: "The file wasn't added.",
    retrySafe: true,
    learnHref: "/learn#bring",
    learnLabel: "Bring in your data",
    dataSafety: "not-added",
  },
  EMPTY_FILE: {
    title: "This file is empty",
    explanation: "FACILIO needs at least one row of tabular data to continue.",
    consequence: "The file wasn't added.",
    retrySafe: true,
    dataSafety: "not-added",
  },
  EMPTY_DATASET: {
    title: "We couldn't read a table from this file",
    explanation: "The file did not contain usable rows and columns.",
    consequence: "The file wasn't added.",
    retrySafe: true,
    dataSafety: "not-added",
  },
  INVALID_CSV: {
    title: "We couldn't read this CSV",
    explanation: "FACILIO currently expects UTF-8 CSV files with a consistent table.",
    consequence:
      "The file wasn't added. Try saving the file as UTF-8 and upload it again.",
    retrySafe: true,
    learnHref: "/learn#bring",
    learnLabel: "Bring in your data",
    dataSafety: "not-added",
  },
  INVALID_JSON: {
    title: "We couldn't read this JSON",
    explanation: "The file is not valid JSON that FACILIO can turn into a table.",
    consequence: "The file wasn't added.",
    retrySafe: true,
    dataSafety: "not-added",
  },
  NON_TABULAR_JSON: {
    title: "This JSON isn't a table FACILIO can use",
    explanation: "FACILIO expects a list of objects with consistent fields.",
    consequence: "The file wasn't added.",
    retrySafe: true,
    dataSafety: "not-added",
  },
  INVALID_WORKBOOK: {
    title: "We couldn't read this spreadsheet",
    explanation: "The workbook could not be opened as tabular data.",
    consequence: "The file wasn't added.",
    retrySafe: true,
    dataSafety: "not-added",
  },
  INVALID_SHEET: {
    title: "That sheet isn't available",
    explanation: "Choose a usable worksheet from this workbook.",
    consequence: "No dataset was created yet.",
    retrySafe: true,
    dataSafety: "not-added",
  },
  INGESTION_FAILED: {
    title: "We couldn't add this file",
    explanation: "FACILIO couldn't store and read this file.",
    consequence: "The file wasn't added.",
    retrySafe: true,
    dataSafety: "not-added",
  },
  CLEANUP_STALE: {
    title: "This cleanup preview is out of date",
    explanation:
      "The selected version changed after the preview was created, or the steps no longer match.",
    consequence:
      "No cleaned version was created. Review the latest version and preview again.",
    retrySafe: true,
    learnHref: "/learn#cleaning",
    learnLabel: "Clean safely",
    dataSafety: "not-created",
  },
  CLEANUP_NOOP: {
    title: "These steps wouldn't change this version",
    explanation: "The selected values already match the requested cleanup.",
    consequence: "No cleaned version was created.",
    severity: "info",
    retrySafe: false,
    learnHref: "/learn#cleaning",
    learnLabel: "Clean safely",
    dataSafety: "not-created",
  },
  TRANSFORMATION_NOOP: {
    title: "These steps wouldn't change this version",
    explanation: "The selected values already match the requested cleanup.",
    consequence: "No cleaned version was created.",
    severity: "info",
    retrySafe: false,
    dataSafety: "not-created",
  },
  WORKFLOW_NOOP: {
    title: "These steps wouldn't change this version",
    explanation: "The selected values already match the requested cleanup.",
    consequence: "No cleaned version was created.",
    severity: "info",
    retrySafe: false,
    dataSafety: "not-created",
  },
  CLEANUP_CONFLICT: {
    title: "Two selected cleanup steps conflict",
    explanation: "These steps cannot both be applied to the same column in one cleanup.",
    consequence: "No cleaned version was created.",
    severity: "warning",
    retrySafe: false,
    learnHref: "/learn#cleaning",
    learnLabel: "Clean safely",
    dataSafety: "not-created",
  },
  CLEANUP_INVALID: {
    title: "This cleanup isn't ready",
    explanation: "One or more selected steps are not valid for this version.",
    consequence: "No cleaned version was created.",
    retrySafe: false,
    learnHref: "/learn#cleaning",
    learnLabel: "Clean safely",
    dataSafety: "not-created",
  },
  INVALID_TRANSFORMATION_PARAMETERS: {
    title: "This cleanup step needs a valid setting",
    explanation: "A selected step is missing a required column or value.",
    consequence: "No cleaned version was created.",
    retrySafe: false,
    dataSafety: "not-created",
  },
  CLEANUP_PREVIEW_FAILED: {
    title: "We couldn't preview these cleanup steps",
    explanation: "FACILIO couldn't show the combined result of the selected steps.",
    consequence: "No cleaned version was created.",
    retrySafe: true,
    learnHref: "/learn#cleaning",
    learnLabel: "Clean safely",
    dataSafety: "not-created",
  },
  PREVIEW_FAILED: {
    title: "We couldn't preview these cleanup steps",
    explanation: "FACILIO couldn't show the result without changing your data.",
    consequence: "No cleaned version was created.",
    retrySafe: true,
    dataSafety: "not-created",
  },
  CLEANUP_HIGH_IMPACT: {
    title: "This cleanup removes many rows",
    explanation: "Confirm if you want to continue. Your original remains unchanged.",
    consequence: "No cleaned version has been created yet.",
    severity: "warning",
    retrySafe: false,
    dataSafety: "not-created",
  },
  CLEANUP_IN_PROGRESS: {
    title: "A cleanup is already running",
    explanation: "Wait for the current cleanup to finish before starting another.",
    consequence: "Your original remains available.",
    severity: "info",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  CLEANUP_FAILED: {
    title: "This cleanup couldn't finish",
    explanation: "FACILIO stopped before creating a cleaned version.",
    consequence: "No cleaned version was created. Your input version is unchanged.",
    retrySafe: true,
    learnHref: "/learn#cleaning",
    learnLabel: "Clean safely",
    dataSafety: "not-created",
  },
  WORKFLOW_EXECUTION_FAILED: {
    title: "This cleanup couldn't finish",
    explanation: "FACILIO stopped before creating a cleaned version.",
    consequence: "No cleaned version was created. Your input version is unchanged.",
    retrySafe: true,
    dataSafety: "not-created",
  },
  TRANSFORMATION_FAILED: {
    title: "This cleanup couldn't finish",
    explanation: "FACILIO stopped before creating a cleaned version.",
    consequence: "No cleaned version was created. Your input version is unchanged.",
    retrySafe: true,
    dataSafety: "not-created",
  },
  UNKNOWN_OPERATION: {
    title: "This cleanup action is no longer available",
    explanation: "The selected step is not a supported FACILIO cleanup action.",
    consequence: "No changes were made.",
    retrySafe: false,
    learnHref: "/learn#cleaning",
    learnLabel: "Clean safely",
    dataSafety: "unchanged",
  },
  UNSUPPORTED_TRANSFORMATION: {
    title: "This cleanup action is no longer available",
    explanation: "The selected step is not a supported FACILIO cleanup action.",
    consequence: "No changes were made.",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  COLUMN_NOT_FOUND: {
    title: "A selected column isn't in this version",
    explanation: "This cleanup refers to a column that is not on the selected data.",
    consequence: "No cleaned version was created.",
    retrySafe: false,
    learnHref: "/learn#cleanups",
    learnLabel: "Reuse a Cleanup",
    dataSafety: "not-created",
  },
  INCOMPATIBLE_COLUMN_TYPE: {
    title: "This step doesn't match the column type",
    explanation: "The selected action can't be applied to this kind of column.",
    consequence: "No cleaned version was created.",
    retrySafe: false,
    dataSafety: "not-created",
  },
  WORKFLOW_INVALID: {
    title: "This cleanup needs attention",
    explanation: "One or more steps are incomplete or invalid.",
    consequence: "Nothing was run against your data.",
    retrySafe: false,
    learnHref: "/learn#cleanups",
    learnLabel: "Reuse a Cleanup",
    dataSafety: "unchanged",
  },
  WORKFLOW_EMPTY: {
    title: "This cleanup has no steps",
    explanation: "Add at least one enabled step before previewing or running.",
    consequence: "Nothing was run against your data.",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  WORKFLOW_INCOMPATIBLE: {
    title: "This cleanup doesn't match the selected data",
    explanation: "The saved steps don't fit this version's columns or types.",
    consequence: "No cleaned version was created.",
    retrySafe: false,
    learnHref: "/learn#cleanups",
    learnLabel: "Reuse a Cleanup",
    dataSafety: "not-created",
  },
  VERSION_NOT_FOUND: {
    title: "This version is no longer available",
    explanation: "Choose the version you want to use and continue from there.",
    consequence: "No additional version was created.",
    retrySafe: false,
    learnHref: "/learn#versions",
    learnLabel: "Understand versions",
    dataSafety: "unchanged",
  },
  DATASET_NOT_FOUND: {
    title: "We couldn't find this dataset",
    explanation: "It may have been deleted, or the link may no longer be valid.",
    consequence: "No dataset was changed.",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  WORKFLOW_NOT_FOUND: {
    title: "We couldn't find this Cleanup",
    explanation: "It may have been deleted, or the link may no longer be valid.",
    consequence: "No Cleanup was changed.",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  JOB_NOT_FOUND: {
    title: "We couldn't find this Activity item",
    explanation: "It may have been removed, or the link may no longer be valid.",
    consequence: "No cleanup was started from this page.",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  WORKFLOW_RUN_NOT_FOUND: {
    title: "We couldn't find this Activity item",
    explanation: "The run record is not available in this workspace.",
    consequence: "No cleanup was started from this page.",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  NOT_FOUND: {
    title: "We couldn't find this page",
    explanation: "This route is not part of the FACILIO workspace, or the item is gone.",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  NETWORK_ERROR: {
    title: "FACILIO can't reach the data service right now",
    explanation: "Some data and actions may be unavailable until the service responds.",
    consequence: "No result was confirmed.",
    retrySafe: true,
    dataSafety: "unknown",
  },
  TIMEOUT: {
    title: "FACILIO didn't get a response in time",
    explanation: "The data service took too long to answer.",
    consequence: "No result was confirmed.",
    retrySafe: true,
    dataSafety: "unknown",
  },
  QUEUE_UNAVAILABLE: {
    title: "FACILIO can't start this cleanup right now",
    explanation: "Background execution is temporarily unavailable.",
    consequence: "No cleaned version was created.",
    retrySafe: true,
    dataSafety: "not-created",
  },
  QUEUE_DISPATCH_FAILED: {
    title: "FACILIO couldn't start this cleanup",
    explanation: "The cleanup was recorded, but it could not be queued for execution.",
    consequence: "No cleaned version was created.",
    retrySafe: true,
    dataSafety: "not-created",
  },
  JOB_RETRY_NOT_ALLOWED: {
    title: "This cleanup can't be retried",
    explanation: "FACILIO only retries when a new attempt is safe and supported.",
    consequence: "No additional version was created.",
    retrySafe: false,
    dataSafety: "unchanged",
  },
  JOB_CANCEL_NOT_ALLOWED: {
    title: "This cleanup can't be cancelled",
    explanation: "Cancellation is only available while a cleanup is waiting or running.",
    retrySafe: false,
    dataSafety: "unknown",
  },
  SAMPLE_NOT_FOUND: {
    title: "The sample dataset isn't available",
    explanation: "FACILIO couldn't load the built-in customer sample.",
    consequence: "No dataset was added.",
    retrySafe: true,
    dataSafety: "not-added",
  },
  NO_NUMERIC_VALUES: {
    title: "This cleanup couldn't finish",
    explanation: "A selected step expected numeric values that were not available.",
    consequence: "No cleaned version was created. Your input version is unchanged.",
    retrySafe: false,
    dataSafety: "not-created",
  },
  CAST_FAILED: {
    title: "This cleanup couldn't finish",
    explanation: "A value could not be converted to the requested type.",
    consequence: "No cleaned version was created. Your input version is unchanged.",
    retrySafe: false,
    dataSafety: "not-created",
  },
};

export const UNKNOWN_FALLBACK: ErrorMapEntry = {
  title: "Something prevented FACILIO from completing this action",
  explanation: "Try again. If the problem continues, open Technical details.",
  retrySafe: true,
  dataSafety: "unknown",
};
